from enum import Enum

class ArmorType(Enum):
    LIGHT = "Light Armor"
    MEDIUM = "Medium Armor"
    HEAVY = "Heavy Armor"
    SHIELD = "Shields"

class WeaponType(Enum):
    SIMPLE = "Simple Weapons"
    MARTIAL = "Martial Weapons"

class Attributes(Enum):
    STR = "Strength"
    DEX = "Dexterity"
    CON = "Constitution"
    INT = "Intelligence"
    WIS = "Wisdom"
    CHA = "Charisma"
    
class Skills(Enum):
    STRENGTH_SAVING_THROW = "Saving Throw"
    ATHLETICS = "Athletics"
    
    DEXTERITY_SAVING_THROW = "Saving Throw"
    ACROBATICS = "Acrobatics"
    SLEIGHT_OF_HAND = "Sleight of Hand"
    STEALTH = "Stealth"
    
    CONSTITUTION_SAVING_THROW = "Saving Throw"
    
    INTELLIGENCE_SAVING_THROW = "Saving Throw"
    ARCANA = "Arcana"
    HISTORY = "History"
    INVESTIGATION = "Investigation"
    NATURE = "Nature"
    RELIGION = "Religion"

    WISDOM_SAVING_THROW = "Saving Throw"
    ANIMAL_HANDLING = "Animal Handling"
    INSIGHT = "Insight"
    MEDICINE = "Medicine"
    PERCEPTION = "Perception"
    SURVIVAL = "Survival"
    
    CHARISMA_SAVING_THROW = "Saving Throw"
    DECEPTION = "Deception"
    INTIMIDATION = "Intimidation"
    PERFORMANCE = "Performance"
    PERSUASION = "Persuasion"
    
    

class ToolTypes(Enum):
    ALCHEMISTS_SUPPLIES = "Alchemist's supplies"
    BREWERS_SUPPLIES = "Brewer's supplies"
    CALLIGRAPHERS_SUPPLIES = "Calligrapher's supplies"
    CARPENTERS_TOOLS = "Carpenter's tools"
    CARTOGRAPHERS_TOOLS = "Cartographer's tools"
    COBBLERS_TOOLS = "Cobbler's tools"
    COOKS_UTENSILS = "Cook's utensils"
    GLASSBLOWERS_TOOLS = "Glassblower's tools"
    JEWELERS_TOOLS = "Jeweler's tools"
    LEATHERWORKERS_TOOLS = "Leatherworker's tools"
    MASONS_TOOLS = "Mason's tools"
    PAINTERS_SUPPLIES = "Painter's supplies"
    POTTERS_TOOLS = "Potter's tools"
    SMITHS_TOOLS = "Smith's tools"
    TINKERS_TOOLS = "Tinker's tools"
    WEAVERS_TOOLS = "Weaver's tools"
    WOODCARVERS_TOOLS = "Woodcarver's tools"
    DICE_SET = "Dice set"
    DRAGONCHESS_SET = "Dragonchess set"
    PLAYING_CARD_SET = "Playing card set"
    THREE_DRAGON_ANTE_SET = "Three-Dragon Ante set"
    BAGPIPES = "Bagpipes"
    DRUM = "Drum"
    DULCIMER = "Dulcimer"
    FLUTE = "Flute"
    LUTE = "Lute"
    LYRE = "Lyre"
    HORN = "Horn"
    PAN_FLUTE = "Pan flute"
    SHAWM = "Shawm"
    VIOL = "Viol"
    DISGUISE_KIT = "Disguise kit"
    FORGERY_KIT = "Forgery kit"
    HERBALISM_KIT = "Herbalism kit"
    NAVIGATORS_TOOLS = "Navigator's tools"
    POISONERS_KIT = "Poisoner's kit"
    THIEVES_TOOLS = "Thieves' tools"
    
class Language(Enum):
    ABYSSAL = "Abyssal"
    AQUAN = "Aquan"
    AURAN = "Auran"
    BARIAUR = "Bariaur"
    CELESTIAL = "Celestial"
    COMMON = "Common"
    DRACONIC = "Draconic"
    DRUIDIC = "Druidic"
    DWARVEN = "Dwarven"
    ELVEN = "Elven"
    GIANT = "Giant"
    GNOME = "Gnome"
    GOBLIN = "Goblin"
    GNOLL = "Gnoll"
    HALFLING = "Halfling"
    IGNAN = "Ignan"
    INFERNAL = "Infernal"
    ORC = "Orc"
    SYLVAN = "Sylvan"
    TERRAN = "Terran"
    KREEN = "Kreen"
    UNDERCOMMON = "Undercommon"